### ISSUE TITLE
feat: make dependency configurable

### ISSUE THREAD

**Issue by danielknell** [artisanofcode/poetry-stickywheel-plugin#5]
## Description

Allow dependency to be configurable

## Context

At the moment the dependency is hard coded to a semver match, it could be configurable to also allow greater-than-equal or exact matches too.

## Possible implementation

```toml
# pyproject.toml

[tool.stickywheel]
strategy = 'semver'
```

| strategy      | version | result        |
| ----------- | -------- | ---------- |
| `semver`    |  `1.2.3` | `^1.2.3`    |
| `minimum` |  `1.2.3` | `>=1.2.3` |
| `exact`       |  `1.2.3` | `1.2.3`      |
